# Generated by Django 3.0.4 on 2020-03-09 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='display_phone',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='price',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='rating',
            field=models.CharField(default='', max_length=10),
        ),
    ]
