# Generated by Django 3.0.4 on 2020-03-09 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_auto_20200309_0605'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='search_url',
            field=models.CharField(default='', max_length=2300),
        ),
    ]
